#
# General settings
#

release-path = 'https://github.com/maude-lang/maude-lang.github.io/releases/download/{ns}/{name}'

[[other-indexed-files]]
name = 'Maude manual'
root = 'manual'
blacklist = ['index.html', 'maude-manual-2.html', 'maude-manualli1.html', 'maude-manualli4.html']

[[other-indexed-files]]
name = 'Old Maude 1 website'
root = 'maude1'

#
# Table of contents
#

[[toc]]
name = 'Home'
page = 'index'

[[toc]]
name = 'Get Maude'
page = 'get-maude'

[[toc]]
name = 'Overview'
page = 'overview'

[[toc]]
name = 'Rewriting logic'
page = 'rewriting-logic'

[[toc]]
name = 'Documentation'
page = 'documentation'

[[toc]]
name = 'Applications'
page = 'applications'

[[toc]]
name = 'Tools'
page = 'tools'

[[toc]]
name = 'Publications'
page = 'publications'
